name: Test & Upload Results

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: '1.19'

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: go get .

      - name: Test with Go
        run: make test-report > TestResults-${{ matrix.go-version }}.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json